[release] angular v10 beta
ant-design/ant-design-icons pull request #320
Opened 2020-06-25 10:51 UTC by wendellhu95

2020-06-25 11:35 UTC, vthinkxie requested changes

2020-06-25 11:35 UTC, vthinkxie commented on packages/icons-angular/src/package.json
>      "@angular/common": "^9.0.0",
peerDependencies needs update too

2020-06-25 14:32 UTC, vthinkxie commented on packages/icons-angular/src/package.json
>      "rxjs": "^6.4.0"
rxjs should also update?

2020-06-25 14:52 UTC, wendellhu95 commented on packages/icons-angular/src/package.json
>      "rxjs": "^6.4.0"
Updated

2020-06-26 13:42 UTC, vthinkxie approved these changes
lgtm

2020-06-26 13:43 UTC, merged